# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0662ed64efefc9fafa0f7c0064711e3e58e506e88a168b4925cff55ef7ef5a0a356b3fc50fb8212f5b93cf7c7c61d3139cd12b2a8ce0f57452eaf31519f49bf3

test:
  secret_key_base: 9ec2a30ad7fdb6891b917cb31523904cc627069cfb342102b248fb11a8e20839d4f77efb5972a56d5cc49fede507df601149557c620d394de0ad455722f08e0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
